name: Analyzing news deadlines with spaCy
description: Demonstrating Named Entity Recognition and some downstream analysis on a Reuters news dataset.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2021-01-12"
api_version: 1
